In [11]:
#Q1:
import numpy as np
import pandas as pd

In [12]:
mat_1=np.array([[5,10,30],[25,35,40],[50,50,40]])
mat_1

array([[ 5, 10, 30],
       [25, 35, 40],
       [50, 50, 40]])

In [13]:
mat_2=np.array([[5,15,9],[25,35,5],[50,6,6]])
mat_2

array([[ 5, 15,  9],
       [25, 35,  5],
       [50,  6,  6]])

In [14]:
Final_Matrix=mat_1+mat_2
Final_Matrix

array([[ 10,  25,  39],
       [ 50,  70,  45],
       [100,  56,  46]])

In [17]:
#Q2:
A=Final_Matrix[1][2]=200
A

200

In [18]:
Final_Matrix

array([[ 10,  25,  39],
       [ 50,  70, 200],
       [100,  56,  46]])

In [19]:
B=Final_Matrix[2][1]=500
B

500

In [20]:
Final_Matrix

array([[ 10,  25,  39],
       [ 50,  70, 200],
       [100, 500,  46]])

In [23]:
#Q3:
from numpy.random import randint as ri
M=ri(21,99,12)
M

array([87, 89, 86, 30, 71, 72, 60, 28, 32, 34, 89, 36])

In [25]:
M.reshape(3,4)

array([[87, 89, 86, 30],
       [71, 72, 60, 28],
       [32, 34, 89, 36]])

In [27]:
M=ri(21,99,12).reshape(3,4)
M

array([[26, 25, 81, 58],
       [38, 43, 23, 96],
       [93, 38, 43, 54]])